using Xunit;

namespace SharpSql.Tests;

public sealed class ProjectCompilerTests
{
    private static string ProjectPath => Path.Combine(
        AppContext.BaseDirectory,
        "fixtures",
        "MultiFileProject",
        "MultiFileProject.csproj");

    [Fact]
    public async Task LoadsAndTranspilesMethodsAcrossProjectDocuments()
    {
        var result = await new SharpSqlProjectCompiler().TranspileAsync(
            ProjectPath,
            new ProjectTranspileOptions
            {
                EntryPoint = "MultiFileProject.SqlJob::Run",
                Configuration = "Release"
            },
            TestContext.Current.CancellationToken);

        Assert.True(result.Success, string.Join(Environment.NewLine, result.Diagnostics));
        Assert.Contains("DECLARE @answer INT", result.Sql);
        Assert.Contains("21 * 2", result.Sql);
        Assert.Contains("project=", result.Sql);
        Assert.DoesNotContain("<auto-generated", result.Sql, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("unrelated overload", result.Sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task DiagnosesAnUnknownProjectEntryPoint()
    {
        var result = await new SharpSqlProjectCompiler().TranspileAsync(
            ProjectPath,
            new ProjectTranspileOptions { EntryPoint = "MultiFileProject.SqlJob::Missing" },
            TestContext.Current.CancellationToken);

        Assert.False(result.Success);
        Assert.Contains(result.Diagnostics, diagnostic => diagnostic.Code == "SS0002");
    }

    [Fact]
    public async Task UsesTheExecutableProjectEntryPointByDefault()
    {
        var result = await new SharpSqlProjectCompiler().TranspileAsync(
            ProjectPath,
            cancellationToken: TestContext.Current.CancellationToken);

        Assert.True(result.Success, string.Join(Environment.NewLine, result.Diagnostics));
        Assert.Contains("21 * 2", result.Sql);
        Assert.Contains("project=", result.Sql);
    }
}
