<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SharpSqlEntryPoint>SdkConsumer.SqlJob::Run</SharpSqlEntryPoint>
    <SharpSqlOutputPath>$(MSBuildProjectDirectory)/generated.sql</SharpSqlOutputPath>
  </PropertyGroup>
</Project>
